#!/bin/bash

JAVA_VERSION=java-1.21.0-openjdk-amd64

sudo update-java-alternatives -s $JAVA_VERSION
export JAVA_HOME=/usr/lib/jvm/$JAVA_VERSION/
export PATH=$PATH:$JAVA_HOME/bin

rm -f *.gz
rm -rf scripts/cas-*
rm -rf scripts/*.gz

./gradlew clean build
